# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-22 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoweliang', '0004_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviewsid',
            new_name='reviewer',
        ),
    ]
