# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-22 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoweliang', '0007_auto_20170522_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='namer',
            new_name='name',
        ),
    ]
